simple router with handler clojures support
zigzap/zap pull request #68
Opened 2024-01-13 12:10 UTC by StringNick

2024-01-17 16:14 UTC, renerocksai commented
Thanks, that's a great PR; I like the example. I hope I'll have more time later to look at it more closely before merging. I'd recommend naming it differently, more descriptively than hello3. Maybe something that communicates mapping routes to handler functions?

Also, please add it to the list of examples in the README, with a short description.

It's a really great example! Also, the `self` hack is genius! :+1:

2024-01-17 21:49 UTC, renerocksai requested changes
Please also document RequestHandler and Router.

2024-01-17 21:49 UTC, renerocksai commented on src/router.zig
> +        var route = self.routes.get(r.path.?);
I think r.path can be null, e.g. when requesting `http://server` as opposed to `http://server/`.

2024-01-17 21:49 UTC, renerocksai commented on src/router.zig
> +pub const RouterOptions = struct {
rename this to Options -> zap.Router.Options

2024-01-17 21:49 UTC, renerocksai commented on src/router.zig
> +pub const Router = struct {
make this the main struct by removing line 31

2024-01-17 21:49 UTC, renerocksai commented on src/zap.zig
> +pub usingnamespace @import("router.zig");
pub const Router = ...

2024-01-17 21:49 UTC, renerocksai commented on src/router.zig
> +pub inline fn RequestHandler(self: anytype, func: *const fn (@TypeOf(self), zap.Request) void) *const fn (zap.Request) void {
maybe, if it should be available under zap namespace, move this into its own file and import in zap usingnamespace.

2024-01-17 21:49 UTC, renerocksai commented on examples/hello3/hello3.zig
> +        .on_request = zap.RequestHandler(&simpleRouter, &zap.Router.serve),
zap.Router.RequestHandler or zap.Requesthandler, depending on whether RequestHandler might be useful outside of zap.Router

2024-01-18 16:51 UTC, StringNick commented
thank you for review and comments, i will fix it, first version name was SimpleRouter, but i saw u refactored names and renamed too, will use SimpleRouter

2024-01-24 12:50 UTC, renerocksai approved these changes
This is looking amazingly good!

2024-01-24 12:50 UTC, merged

2024-01-24 13:12 UTC, renerocksai commented
Thx for the great work. Now, if you're up for it, could you please add doc comments for the zap.Router? Best take the zig-0.12.0 branch for that, as I fixed some const issues there (new zig is const-mad).