Provide Windows error message
zigzap/zap pull request #75
Opened 2024-01-31 15:42 UTC by Froxcey

Yes, it is already in README. I just thought it would be nice if the build system explicitly fails Windows builds.

Just 2 LOC, thanks to Zig's beautiful build system.

Just wanna mention #74 

<img src="https://github.com/Avdan-OS/Compositor/assets/51555391/d0379882-f2dc-42e1-962f-b3f122db656f" alt="vibe" width="60"/>

2024-02-03 14:32 UTC, renerocksai requested changes
I want to merge this so you get the recognition.

# **AWESOME IDEA** :+1:  :+1:  :+1:  :partying_face: 

I really like it!

2024-02-03 14:32 UTC, renerocksai commented on build.zig
> +        @panic("Facil (and Zap) doesn't support Windows, at least not currently. Try targeting Linux and using WSL\n");
Please rephrase like: "Currently, Facil.io and Zap are not compatible with Windows. Consider using Linux or Windows Subsystem for Linux (WSL) instead."

2024-02-12 08:37 UTC, Froxcey commented
Sorry, I was kind of on a vacation. Anyways, it should be good now

<img width="1025" alt="Example" src="https://github.com/zigzap/zap/assets/51555391/9bb74a25-4003-4970-83bd-4af0921166f1">

2024-02-12 09:51 UTC, Froxcey commented
Btw I saw your talk on Showtime, and I just want to say it's awesome :D

2024-02-12 16:28 UTC, Froxcey commented
Should `@panic` or `std.log.err` message be used? 

The difference lies in that `@panic` gives a stack trace pointing to the build script where `@panic` is invoked, whereas `std.log.err` + `std.os.exit` seems cleaner. Here are the screenshots:

`@panic`:
<img width="1276" alt="Version one" src="https://github.com/zigzap/zap/assets/51555391/6c98865b-81ed-44d5-8499-e51499ff7c82">

`std.log.err` + `std.os.exit`:
<img width="1280" alt="Version two" src="https://github.com/zigzap/zap/assets/51555391/d998be17-ca46-43f0-8c87-a60e20c4307c">

I personally prefer `std.log.err` + `std.os.exit` because the stack trace is not really adding any useful information to the already self-explanatory error message. I want the crash message to be beautiful, so I will convert this to a Draft PR temporarily before a decision is made.

2024-02-19 12:39 UTC, Froxcey commented
I just committed the version with less chunky error message

2024-02-22 20:09 UTC, renerocksai approved these changes
Sorry so late but looks really good

2024-02-22 20:09 UTC, merged